---
title: "Final Project"
author: "Daniel Chelling"
subtitle: MGSC 310 Project 
output:
  html_document:
    df_print: paged
  html_notebook: default
---


```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```


<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

library("here")
library("tidyverse")
library("forcats")
library("rsample")
library("ggplot2")
library("ggmap")
library("dplyr")
library("lubridate")
library("xgboost")
library('DiagrammeR')
library('Matrix')

```



```{r}

crashes <- read.csv(here("datasets", "US_Accidents_Dec20_updated.csv"))


```

```{r}

summary(crashes)


```

```{r}


crashes_clean <-
  crashes %>% 
  mutate(Start_Time_Clean = ymd_hms(Start_Time),
         End_Time_Clean = ymd_hms(End_Time),
         Weather_Condition_Clean = as.factor(Weather_Condition),
         Wind_Direction_Clean = as.factor(Wind_Direction),
         Weather_Timestamp_Clean = ymd_hms(Weather_Timestamp),
         State_Clean = as.factor(State),
         County_Clean = as.factor(County),
         City_Clean = as.factor(City),
         Side_Clean = as.factor(Side))
  

summary(crashes_clean)


```


```{r}

qmplot(Start_Lng, Start_Lat, data = crashes, maptype = "toner-lite", color = factor(Severity))

qmplot(End_Lng, End_Lat, data = crashes, maptype = "toner-lite", color = factor(Severity))


```

```{r}

ggplot(data = crashes_clean, aes(x = Severity)) + geom_histogram()



```

```{r}

ggplot(data = crashes_clean, aes(x = Start_Time_Clean, y = Distance.mi.)) + geom_line()


```

```{r}

crashes_clean %>% 
  ggplot(aes(Start_Time_Clean)) + geom_histogram(binwidth = 86400)

```

```{r}

crashes_clean %>% 
  mutate(wday = wday(Start_Time, label = TRUE)) %>% 
  ggplot(aes(x = wday)) +
    geom_bar()



```



```{r}

crashes_split <- initial_split(crashes_clean, prop = 0.75)

crashes_train <- training(crashes_split)
crashes_test <- testing(crashes_split)


```

```{r}

crashes_xgb <- crashes %>% 
  select(-ID,
         -Description,
         -Street,
         -Weather_Timestamp,
         -Number,
         -Airport_Code,
         -Country,
         -Turning_Loop) %>% 
  drop_na()

crashes_split_xgb <- initial_split(crashes_xgb, prop = 0.75)

crashes_train_xbg <- training(crashes_split_xgb)
crashes_test_xbg <- testing(crashes_split_xgb)


sparse_matrix_train <- sparse.model.matrix(Severity ~ .-1, data = crashes_train_xbg)
sparse_matrix_test <- sparse.model.matrix(Severity ~ .-1, data = crashes_test_xbg)


y_train <- as.integer(crashes_train_xbg$Severity) - 1
y_test <- as.integer(crashes_test_xbg$Severity) - 1

xgb_train <- xgb.DMatrix(data = sparse_matrix_train, label = y_train)
xgb_test <- xgb.DMatrix(data = sparse_matrix_test, label = y_test)


```

```{r}

xgb <- xgboost(data = xgb_train,
 eta = 0.1,
 max_depth = 15, 
 nround=15, 
 subsample = 0.5,
 colsample_bytree = 0.5,
 seed = 1,
 eval_metric = "merror",
 objective = "multi:softprob",
 num_class = 12,
 nthread = 3
)

```



```{r}

y_pred <- predict(xgb, newdata = xgb_train)
print(length(y_pred))
print(head(y_pred))

```

```{r}

err <- mean(as.numeric(y_pred > 0.5))
print(paste("test-error=", err))


```

```{r}


tree_plot <- xgb.plot.tree(model = xgb, trees = 1, feature.keep = 3)

tree_plot


```
```{r}

importance_matrix <- xgb.importance(model = xgb)
xgb.plot.importance(importance_matrix)


importance_matrix
```